#!/bin/bash
#Arjienx Advanced DNSTT Script v0.1.5x Installer 2024

cd ~
rm -rf install
architecture=$(uname -m)
echo "Architecture: $architecture"

if [ ! -d "$HOME/storage" ]; then
    termux-setup-storage
fi

version=$(getprop ro.build.version.release)
if [[ "$version" =~ ^5.* || "$version" =~ ^6.* ]]; then
    echo "deb https://packages.termux.dev/termux-main-21/ stable main" > "$PREFIX/etc/apt/sources.list"
    echo "deb https://termux.dev/game-packages-21-bin games stable" > "$PREFIX/etc/apt/sources.list.d/game.list"
    echo "deb https://termux.dev/science-packages-21-bin science stable" > "$PREFIX/etc/apt/sources.list.d/science.list"
    clear
else
    echo "Current version: $version"
fi

apt update
apt upgrade -y openssl curl
apt install -y dnsutils nano curl

if command -v go &> /dev/null && [ "$(go version | awk '{print $3}' | cut -d 'v' -f 2)" == "go1.21.3" ]; then
    echo "Go version 1.21.3 is already installed."
else
    echo "Installing Go version 1.21.3..."
    rm -rf "$PREFIX/go"
    curl --insecure -o go1.21.3.linux-arm64.tar.gz "https://dl.google.com/go/go1.21.3.linux-arm64.tar.gz"
    tar -C "$PREFIX" -xzf "go1.21.3.linux-arm64.tar.gz"
    ln -sf "$PREFIX/go/bin/go" "$PREFIX/bin/go"
    rm -rf "go1.21.3.linux-arm64.tar.gz"
    echo "Go version 1.21.3 installed."
fi

echo "" > ../usr/bin/menu
curl --insecure -o ../usr/bin/izph https://raw.githubusercontent.com/arjienx/termux/main/izph && chmod +x ../usr/bin/izph
grep -qxF "alias izph='cd ~ && izph'" ~/.bashrc || echo "alias izph='cd ~ && izph'" >> ~/.bashrc
source ~/.bashrc

echo "Successfully Installed."
echo
echo "IZPH - Arjienx Advanced DNSTT Script v0.1.5x"
echo
echo "Architecture: $architecture"
echo "type 'izph' to run the dnstt termux script."
